version: '3.8'
services:
  front:
    build:
      context: ./front/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
  api:
    env_file:
      - api/.env
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000